### PR TITLE
Create new checkbox input and replace all the existing ones with it

### PR DESCRIPTION
**Pull request by axbarsan**
Towards giantswarm/giantswarm#11004 and towards the grommet migration

As previously, this includes the new component, snapshot tests, Storybook examples and also replaces all the existing checkbox inputs with the new one.

### Preview

<details>
<summary>With label</summary>

image

</details>

<details>
<summary>With label - checked</summary>

image

</details>

<details>
<summary>With form field label</summary>

image

</details>

<details>
<summary>With error</summary>

image

</details>

<details>
<summary>With info</summary>

image

</details>

<details>
<summary>With help</summary>

image

</details>

<details>
<summary>Disabled</summary>

image

</details>

<details>
<summary>Toggle mode - off</summary>

image

</details>

<details>
<summary>Toggle mode - on</summary>

image

</details>

### CODE REVIEW

**Comment by marians** [comment]
How does a checked box look like?

**Comment by oponder** [comment]
@marian like this:

Screenshot 2021-02-16 at 6 39 35 PM

**Comment by axbarsan** [comment]
> How does a checked box look like?

Ah yes, the most important part 😬 I updated the PR description

**Review by oponder — APPROVED** [review]
LGTM! (Looks GREAT to me)

**Review by marians — APPROVED** [review]

**Comment by marians** [comment]
Thank you!

**Comment by marians** [comment]
Heads-up: Since this is a user-facing change, it should be included in the changelog. Based on the labels it's not in the current draft.

**Comment by oponder** [comment]
ok I added it to the release draft manually.

**Pull request merged**
