### PR TITLE
Disabled number picker buttons

### PR DESCRIPTION
**Pull request by ograu**
Buttons " + " and " - " will be disabled once the value in the input equals maximum and minimum value respectively.

@marians I've used same styling that we have for disabled buttons, not thrilled though

### CODE REVIEW

**Comment by ograu** [comment]
And now it is possible to delete the input with backspace key, it will mark the form as invalid and so it cannot be submitted

**Comment by oponder** [comment]
I think the state is still kinda going through, and being validated against the invalid state... so like when I click beyond the allowed range i get the validation error, even though the number didnt change and the button was disabled.

To be a bit clearer, I can click on it in the disabled state, which leads to the validation error showing, but the number not changing.

**Comment by oponder** [comment]
Maybe add a bit of blue to the gray so it doesn't stand out that much?

556677
Screenshot 2019-09-26 at 5 01 49 PM

Instead of 888888
Screenshot 2019-09-26 at 5 02 28 PM

**Comment by ograu** [comment]
Sorry I forgot the image, this is how it looks now:

Captura de pantalla 2019-09-26 a las 16 45 51

> To be a bit clearer, I can click on it in the disabled state, which leads to the validation error showing, but the number not changing.

I know, I have followed @marians instructions, if I undestood them well... IMO it feels better or more natural to me now.

**Comment by oponder** [comment]
But the thing is I can put the form into an invalid state, even though the number picker hasn't changed to an invalid value. Then I have to click to subtract one (and the picker still shows 3) to enable to 'submit' button again.

**Comment by oponder** [comment]
Oh! I'm looking at the number picker on the create cluster page, maybe it's behaving differently there

**Comment by ograu** [comment]
Same behaviour in both places

> But the thing is I can put the form into an invalid state, even though the number picker hasn't changed to an invalid value. Then I have to click to subtract one (and the picker still shows 3) to enable to 'submit' button again.

Oh, I get you now! fixing it

**Comment by ograu** [comment]
> Maybe add a bit of blue to the gray so it doesn't stand out that much?
> 
> 556677
> Instead of 888888

I don't know, let's see what Marian says... If it doesn't stand out that much (I don't like it either, at least with these styles) it's not evident that has changed its state... plus I would like to be consistent with the colors

**Comment by ograu** [comment]
@oponder @marians Can we merge it and decide the colors later?

**Comment by marians** [comment]
I'll check

**Comment by marians** [comment]
Yeah, the gray for a disabled up/down button is pretty much highlighting the button right now, instead of dimming it. I suggest `rgb(60, 90, 113)` or `#3c5a71`.

**Comment by marians** [comment]
After I looked for a color I saw that @oponder already has suggested one. `556677` works for me, too.

**Comment by ograu** [comment]
Changed

**Pull request merged**
