### PR TITLE
Allow user input in number picker.

### PR DESCRIPTION
**Pull request by oponder**
Towards: https://github.com/giantswarm/giantswarm/issues/3824

Also fixes some styles for KVM's create cluster screen:

before:
screenshot 2018-12-07 at 17 29 04

after:
screenshot 2018-12-07 at 17 26 48

### CODE REVIEW

**Comment by marians** [comment]
Will test this now

**Comment by oponder** [comment]
No strong reason, will add it!

**Comment by marians** [comment]
Thanks!

**Comment by xh3b4sd** [comment]
I like the more extensive comments in the component that explain why things are how they are. That is really useful. Thank you.

**Pull request merged**
