### PR TITLE
Fix app creation, wrong method after refactor

### PR DESCRIPTION
**Pull request by oponder**

### CODE REVIEW

**Comment by oponder** [comment]
App catalog tests coming in soon so we can catch something like this in the future.

**Comment by oponder** [comment]
fyi @axbarsan, happened here: https://github.com/giantswarm/happa/pull/913/files#diff-88613a75860525c161896b51b7dc845bR99

I didn't notice it when approving :P , but upcoming tests will catch it.

**Comment by oponder** [comment]
Gonna go ahead and merge with a ping @giantswarm/sig-front-end

**Comment by oponder** [comment]
Oh no I cant :P

**Comment by axbarsan** [comment]
I apologize for not catching this earlier 😢

**Comment by oponder** [comment]
> I apologize for not catching this earlier 😢

Nah I apologise for not having tests in that area!

**Pull request merged**
