### PR TITLE
Various testing changes

### PR DESCRIPTION
**Pull request by ubergesundheit**
I'm trying out code splitting with Suspense

### CODE REVIEW

**Comment by ubergesundheit** [comment]
Hey fellow @giantswarm/chapter-front-end people,

I also think we should discuss in next sync if we want to have lazy loading with Suspense. Could you take a look?

Please take a look at the changes I've made to [testUtils/setupTests.js](https://github.com/giantswarm/happa/pull/1124/files#diff-be2822115402ddeaa7d95a77f46b0d97)

Also, I cannot figure out how to fix the `__tests__/SignUp.js` test. Here's what's happening (I think):

- Loading of components is delayed, so the api mocks won't get used, so they're still pending
- When some of the nock mocks are removed, tests succeed, but `selectAuthToken` in [testUtils/modelMocks.js](https://github.com/giantswarm/happa/blob/bf6d83f8ef9e355d4c1eb0423bbd2b639ea7caee/testUtils/modelMocks.js#L8-L10) fails because `state.main.loggedInUser.auth` does not contain a `token`. Using `?.` does not fix this.

**Comment by oponder** [comment]
Im not really seeing an effect from this (deployed it to ginger to check it out), I was expecting to see like multiple network requests, to fetch different parts of the app, and possibly a reduction in the initial request size, but to me it still looks like everything is loading at once?

Can you explain a bit more what should be happening and kind of what the before/after change is as a result of introducing this?

I think showing some data on the benefits would help get the PR moving forward towards acceptance.

Really cool that you introduce this and make some effort on that though!!

**Comment by ubergesundheit** [comment]
I did some comparisons with the current state of this branch and with all `<Suspense>` and `React.lazy` removed.

How I did it:

## General commands used

```
rm -rf dist
yarn webpack --config webpack.prod.js
docker build -t happa:with-suspense .
docker run -e API_ENDPOINT=http://localhost:8000 -e PASSAGE_ENDPOINT=http://localhost:5001 -e INGRESS_BASE_DOMAIN=yolo -e AWS_CAPABILITIES_JSON={} -e AZURE_CAPABILITIES_JSON={} -e ENVIRONMENT=cool --rm -it -p 7000:8000 happa:with-suspense
```

## File sizes

File sizes are determined using this command

```
du -b -a dist/**/*.js | sort -n -r
```

### Without Suspense

```
1723804	dist/assets/vendors~main.deba8bd03ee0.js
1169692	dist/assets/main.ba96fb78bce2.js
2670	dist/vendor/modernizr.js
113	dist/images/index.js
```

### With Suspense

```
851151	dist/assets/vendors~main.d1a2c1a692a9.js
549896	dist/assets/Organizations.545697021f77.js
259325	dist/assets/vendors~Layout.8e34ca49bc19.js
219452	dist/assets/vendors~Organizations.a32812e4c498.js
170631	dist/assets/main.5bf9cb66a6ef.js
158362	dist/assets/Layout.4ecea8c79013.js
123277	dist/assets/vendors~Organizations~Users.9c57f1ecc2ea.js
103414	dist/assets/0.e254ac1cd87a.js
90848	dist/assets/AppCatalog.238c7996056b.js
62592	dist/assets/vendors~AppCatalog~Organizations~StyleGuide.9644c574b82e.js
62048	dist/assets/vendors~AppCatalog.2499cd4e032d.js
45548	dist/assets/Layout_Home.4b52e2585989.js
43324	dist/assets/Users.f84786c75c07.js
41286	dist/assets/28.b3c20aca057c.js
32197	dist/assets/23.5193dd5dc2de.js
31077	dist/assets/AccountSettings.9215716453e8.js
28880	dist/assets/Login.7658783879c6.js
27662	dist/assets/7.4c75f467caa8.js
22438	dist/assets/vendors~Users.834d0aeeabac.js
22366	dist/assets/StyleGuide.ef6f967573c5.js
20884	dist/assets/24.d11c8c9e6e12.js
18707	dist/assets/29.cde18e0a8db9.js
14118	dist/assets/25.5e51bb170a83.js
10964	dist/assets/AdminLogin.0b139c126ef8.js
10323	dist/assets/27.eaaff3c8fc8f.js
10323	dist/assets/26.c1610f1cb277.js
9747	dist/assets/1.984ed6e66b81.js
8811	dist/assets/AppCatalog~StyleGuide.0e45646e43d1.js
8227	dist/assets/vendors~Layout_Home~Organizations.b493445de0d4.js
3254	dist/assets/AppCatalog~Layout_Home.c21df4dd0396.js
2670	dist/vendor/modernizr.js
113	dist/images/index.js
```

## Loading / in Firefox

With Dev tools open. `Disable cache` checked. Only JS files from `localhost`. Local API with 15 clusters.

Interesting numbers are on the bottom of the screenshots

### Without Suspense

image

### With Suspense: Loading / in Firefox

image

### With Suspense: Loading /organizations in Firefox

Because it seems to be the biggest chunk based on the file sizes above.

image

**Comment by ubergesundheit** [comment]
As it was already said in our last chapter meeting, the changes are not really noticable. Merging this wouldn't hurt but removing unneccessary dependencies would help more.

**Comment by axbarsan** [comment]
The results look good to me, I would move forward with this.

However, I think we should implement a retry system for chunks, because as you know, some requests just time out for our customers in China, and the app would not work if a chunk fails to load.

**Comment by ubergesundheit** [comment]
For now I've decided to remove the Suspense/lazy loading of Components. But the PR contains some good stuff mostly test related (courtesy of @axbarsan). So I it would be good to have this merged.

**Pull request merged**
