### PR TITLE
Set check icon color for RadioButton

### PR DESCRIPTION
**Pull request by marians**
This PR sets the inner color of a selected radio button to highlight the selected item more. This should prevent users from wondering which one is the active (selected) one when there are exactly two options. (We had this reported)

## Status Quo

image

## Preview

image

### CODE REVIEW

**Comment by marians** [comment]
@axbarsan @oponder Help appreciated, however not at all urgent.

**Review by axbarsan — CHANGES_REQUESTED** [review]
There's the `icon` property a bit lower in the file that needs to be modified.

```diff
icon: {
-      extend: (props: { theme: ThemeType }) => {
-        const fillColor = props.theme.global!.colors!.text!;
-        let colorHex = '';
-        if (typeof fillColor === 'string') {
-          colorHex = fillColor;
-        } else {
-          colorHex = fillColor.dark!;
-        }
-
-        return {
-          fill: colorHex,
-        };
-      },
+      extend: () => css`
+        fill: ${(props) => props.theme.global!.colors!['input-highlight']};
+      `,
    },
```

**Comment by marians** [comment]
Thank you!

**Review by axbarsan — APPROVED** [review]

**Review by axbarsan — APPROVED** [review]
Nice

**Pull request merged**
