### PR TITLE
Rename admin group

### PR DESCRIPTION
**Pull request by axbarsan**
This is different now

### CODE REVIEW

**Review by corest — COMMENTED** [review]
we have this hardcoded in too many places :/

**Comment by axbarsan** [comment]
> we have this hardcoded in too many places :/

You're right, there's no reason to not get the group value from `draughtsman`. I'll update this PR

**Review by oponder — APPROVED** [review]
LGTM, up to you if you wanna merge this, or make the draughtsman edit

**Comment by axbarsan** [comment]
Ah shit had auto-merge on FFS

**Comment by oponder** [comment]
Oh sorry buddy! 😢

**Pull request merged**
