### PR TITLE
Increase KVM min requirements to 4 CPU and 4GB

### PR DESCRIPTION
**Pull request by sslavic**
Towards https://github.com/giantswarm/giantswarm/issues/5063

### CODE REVIEW

**Comment by oponder** [comment]
@sslavic This can be merged right?

**Comment by sslavic** [comment]
@oponder I think not yet, see https://github.com/giantswarm/giantswarm/issues/5063#issuecomment-593946309

**Comment by oponder** [comment]
This is about KVM though. Not sure what the blocker is there based on that comment you linked. Or do you want to merge everything at once and announce to the customer at once?

**Comment by sslavic** [comment]
@oponder yeah, what Marian documented as necessary sub-tasks is involving process, don't want to miss something in a hurry - figuring out announcement with @cokiengchiara, finding existing kvm clusters with 2 CPU workers and changing them to new min of 4 - while I'd like to finish enabling HPA for nginx first, since it currently block shipping other legacy releases for all 3 providers; if you and/or @cokiengchiara can help with the the announcement (maybe see as basis similar recent announcement where 2CPU AWS instance types were removed), merging/releasing these 3 CP components if I'm not mistaken should be trivial, and I can as follow up go and bump existing 2CPU clusters.

Related PRs that need to be merged too:
- https://github.com/giantswarm/api/pull/995
- https://github.com/giantswarm/cluster-service/pull/414

**Comment by cokiengchiara** [comment]
We decided not to ship this for technical reasons. But for the future person who will, can use this draft of release notes https://www.dropbox.com/scl/fi/zkscmflr5h1x4wnt9cxmv/Announcement_-Adjust-VM-size_instance-type-defaults-and-minimal-RAM-and-CPU-for-worker-nodes-to-4-GB-and-4-CPUs.paper?dl=0&rlkey=psiclzim0qllxg3usq4msyrvz

**Pull request closed without merging**
