### PR TITLE
Add a login test.

### PR DESCRIPTION
**Pull request by oponder**
This adds an integration test for logging in.

The boundary are the actual network requests to the API, which are mocked using `nock`. 
Nock works by overriding Node's http.request function. 

https://github.com/nock/nock

The stuff under `GIVEN` could be extracted somehow into a 'Happy API setup' function somehow.

Since I think we will be repeating it often.

### CODE REVIEW

**Comment by oponder** [comment]
Fails currently in circleci, since I need to get it running a later version of node. (Array.flat is not a function)

**Comment by ograu** [comment]
> The stuff under `GIVEN` could be extracted somehow into a 'Happy API setup' function somehow.
> 
> Since I think we will be repeating it often.

Cool! Love the approach ❤️ 

So if I understand it well `nock` will intercept all requests that match with the route passed as an argument, righ?

This way we could define diferent responses in each case, which is great.
Thanks!

**Comment by oponder** [comment]
> So if I understand it well nock will intercept all requests that match with the route passed as an argument, righ?

Correct!

> This way we could define diferent responses in each case, which is great.

Yup! And it even complains if the same request happens more than once, so for each request (even to the same endpoint) you have to make a nock like that. 

So you could even test (if we increase the jest timeout for that page) the pages that do like refreshing requests to `/v4/clusters` and pretend that one of the requests fails or something like that.

It will also reveal if we are making requests we don't expect for a certain path.. the errors are pretty helpful so far.

**Comment by oponder** [comment]
FYI @marians , this might be a usable test example you've been waiting for.

**Pull request merged**
