### PR TITLE
Create component for availability zones label

### PR DESCRIPTION
**Pull request by marians**
This component should be re-usable to display which AZs a cluster or node pool uses.

## Preview

image

The full zone name, e. g. `eu-central-1b`, is shown on mouse over.

### CODE REVIEW

**Comment by oponder** [comment]
Shouldn't this be in the UI folder :) ?

**Comment by marians** [comment]
Yes, indeed. I forgot to move.

**Comment by oponder** [comment]
I just noticed that `abbr` gets `cursor: help` from bootstrap applied to it. Which shows the cursor as a 'question mark' when hovering over these Availability Zones. Did you notice that? Is that something you want to keep?

**Comment by marians** [comment]
@oponder I was aware and I didn't mind.

**Pull request merged**
