### PR TITLE
Fetch everything at once with await

### PR DESCRIPTION
**Pull request by ograu**
This is my take on what we are PRing in `fetch-everything-at-once`: it is the same you did but using await and because of that a little more readable in my opinion.

### CODE REVIEW

**Comment by oponder** [comment]
Thx oriol! I like this approach more. I will merge it later, want to do some exploratory testing to see how it handles certain error edge cases. (mostly because I need to understand better (await / async) and will probably learn a lot

**Comment by ograu** [comment]
ping @oponder 

Do you think we can merge it into master? I have to work with this `clustersLoadV4()` function now and find it a little bit difficult to follow.

**Comment by oponder** [comment]
There was a problem with this version, which is fixed here: https://github.com/giantswarm/happa/pull/732

Also the client has changed slightly, it doesn't need to take `sheme + token` as a parameter anymore:

https://github.com/giantswarm/happa/pull/733

So this is a bit outdated now. Merging it as is will introduce some regressions.

If you want I can try to change what we have now into async await, using this as an example.

**Comment by ograu** [comment]
I am doing it, thanks!

**Comment by ograu** [comment]
continued in https://github.com/giantswarm/happa/pull/744

**Pull request closed without merging**
