### PR TITLE
Add information about Kubernetes versions' EOL status

### PR DESCRIPTION
**Pull request by axbarsan**
Towards https://github.com/giantswarm/giantswarm/issues/13439

This PR adds support for displaying if a Kubernetes version reached its end of life or not, in various places.

### Cluster overview

<details>
<summary>EOL version</summary>

image

</details>

<details>
<summary>EOL version (hover)</summary>

image

</details>

<details>
<summary>Soon to be EOL version</summary>

image

</details>

<details>
<summary>Soon to be EOL version (hover)</summary>

image

</details>

### Cluster details

<details>
<summary>EOL version</summary>

image

</details>

<details>
<summary>EOL version (hover)</summary>

image

</details>

<details>
<summary>Soon to be EOL version</summary>

image

</details>

<details>
<summary>Soon to be EOL version (hover)</summary>

image

</details>

### Cluster details - Release details

<details>
<summary>EOL version</summary>

image

</details>

<details>
<summary>Soon to be EOL version</summary>

image

</details>

### Cluster details - Apps

<details>
<summary>EOL version</summary>

image

</details>

<details>
<summary>Soon to be EOL version</summary>

image

</details>

### Cluster creation - Release selection

<details>
<summary>EOL version</summary>

image

</details>

<details>
<summary>Soon to be EOL version</summary>

image

</details>

### Cluster creation - Release selection - Available releases

<details>
<summary>EOL version</summary>

image

</details>

<details>
<summary>EOL version (hover)</summary>

image

</details>

<details>
<summary>Soon to be EOL version</summary>

image

</details>

<details>
<summary>Soon to be EOL version (hover)</summary>

image

</details>

### CODE REVIEW

**Review by oponder — APPROVED** [review]
LGTM and WFM, code and UX wise.

**Comment by oponder** [comment]
Thanks also for the thoroughness in the screenshots. Great context setting for what the PR will do.

**Comment by marians** [comment]
What do you think about making this appear a bit more graphical? Like here:

image

The color might need some tweaking.

However, in this context ...

image

it might be a bit too much to cram in another tag into the component, so maybe here the `(EOL)` in brackets is better suited.

**Comment by marians** [comment]
And +1 for @oponder `s comment on the great reviewer support!

**Comment by axbarsan** [comment]
> What do you think about making this appear a bit more graphical? Like here:
> 
> image

I like that, I made the changes and updated the screenshots.
Check:

* Cluster overview
  * EOL version
  * EOL version (hover)
* Cluster details
  * EOL version
  * EOL version (hover)
* Cluster creation - Release selection - Available releases
  * EOL version
  * EOL version (hover)

**Comment by marians** [comment]
Nice! A bit of tweaking:

image

image

That is 

- smaller font size
- padding vertical 1px instead of 0
- margin-left 5px instead of 4px
- border-radius 3px instead of 4px
- font-weight 400 instead of 300

**Comment by axbarsan** [comment]
> That is
> 
> * smaller font size
> * padding vertical 1px instead of 0
> * margin-left 5px instead of 4px
> * border-radius 3px instead of 4px
> * font-weight 400 instead of 300

Pixel-perfect 😅 Updated the screenshots

**Review by marians — APPROVED** [review]

**Pull request merged**
