### PR TITLE
Access control UI tweaks

### PR DESCRIPTION
**Pull request by marians**
Some attempts to improve the access control UI.

- Change of column widths: Narrower role list, wider right hand side. Less truncation. No more resource count. (https://github.com/giantswarm/giantswarm/issues/16462)
- Use monospaced font in permissions table
- Use unicode character for ellipsis in truncation and in permission verbs

## Preview

image

### CODE REVIEW

**Review by oponder — APPROVED** [review]
LGTMIIWFY

**Comment by marians** [comment]
Actually I just noticed that I don't like summary terms like "All" showing up in monospaced. It's not a literal value. Will tweak that.

**Comment by marians** [comment]
Changed and also updated the preview image.

As a side effect, we now only use the `<Truncated>` component if there is a string to be truncated, but not for the `All` case.

**Comment by marians** [comment]
@axbarsan Could you please review this? Since it's mostly your work I am modifying.

**Review by axbarsan — APPROVED** [review]
LGTM

**Pull request merged**
