### PR TITLE
Allow for node pools with zero nodes

### PR DESCRIPTION
**Pull request by paurosello**
**IMPORTANT: The changelog for the next release is generated automatically, based on pull requests merged to `master`. In order to properly categorize the changes made, you should allocate a proper label to your pull request:**

- Introducing a new feature

  - `kind/feature`

- Changing existing functionality

  - `kind/change`
  - `kind/ux-enhancement`

- Soon-to-be removed features

  - `kind/deprecation`

- Removing features

  - `kind/removal`

- Fixing bugs

  - `kind/bug`

- Fixing vulnerabilities
  - `kind/security`

**Excluded from changelog**

- `dependencies` (Updating dependencies)
- `kind/dev-change` (Changing development commands, file structure, etc.)
- `kind/refactor` (Improving the implementation of a specific part of the codebase, without changing its functionality)

### CODE REVIEW

**Comment by paurosello** [comment]
Do i need to put Changelog somewhere? not sure about the release process here

**Comment by paurosello** [comment]
Related to https://github.com/giantswarm/roadmap/issues/234

**Comment by marians** [comment]
@paurosello Here the title of the PR gets added to the next happa release. Suggestion: `Allow for node pools with zero nodes`

**Comment by paurosello** [comment]
Cool, changed it

**Review by axbarsan — APPROVED** [review]

**Comment by paurosello** [comment]
Towards https://github.com/giantswarm/roadmap/issues/234

**Pull request merged**
