### PR TITLE
App Catalog Feature

### PR DESCRIPTION
**Pull request by oponder**
This is a collection of two accepted app catalog related PRs for Happa

- Showing the app catalog: https://github.com/giantswarm/happa/pull/526
- Showing installed apps in the cluster detail page: https://github.com/giantswarm/happa/pull/574

Installing Apps & Deleting Apps will come next. But I'd like to avoid stacking too much stuff on top of each other and already get feedback on this.

Towards: giantswarm/giantswarm#4848

### CODE REVIEW

**Comment by oponder** [comment]
All code in here already accepted. Not sure what you would prefer to do in cases of these types of feature branches made up of multiple PRs... have one final approve? or ok to just merge?

I'll change the giantswarm-js-client to master once https://github.com/giantswarm/api-spec/pull/135 is approved.

**Comment by marians** [comment]
I'll deploy it on gauss and ghost for a last check

**Comment by marians** [comment]
What else is needed to make the feature show up? How to add a catalog?

**Comment by oponder** [comment]
Add a `appcatalog` cr to the installation as follows:


```
# helm.yaml
apiVersion: application.giantswarm.io/v1alpha1
kind: AppCatalog
metadata:
  name: helm
spec:
  description: The helm/stable repository contains a large number of charts. Giant Swarm offers no SLA on these apps/charts. Proceed with caution.
  logoURL: /images/repo_icons/community.png
  storage:
    URL: https://cors-anywhere.herokuapp.com/https://kubernetes-charts.storage.googleapis.com/
    type: helm
  title: Community
```


`kubectl apply -f helm.yaml`

**Comment by oponder** [comment]
I had a bit of a merge fiasco.. fixing.

**Pull request merged**
