### PR TITLE
Remove ESLint no-use-before-define

### PR DESCRIPTION
**Pull request by ograu**
Are you ok deleting this? I think it doesn't make much sense ...

### CODE REVIEW

**Comment by oponder** [comment]
This would stop us from using variables before we define them.. I think that makes a lot of sense right?

Do you have some code snippets where this rule triggers in a way you don't like?

**Comment by ograu** [comment]
I don't like that it is giving us a lot of false positives in functions.

I've changed it, ¿Does it makes sense now?

**Comment by ubergesundheit** [comment]
I guess I'm on the same page as @oponder that this is an useful rule to keep. Even though all the code we write in happa gets transpiled and minified down, still I think having this rule as an error for all usage befor define make sense

**Comment by ograu** [comment]
> I guess I'm on the same page as @oponder that this is an useful rule to keep. Even though all the code we write in happa gets transpiled and minified down, still I think having this rule as an error for all usage befor define make sense

Not sure if I understand it, then ¿Are you ok with what I am proposing?

**Comment by ubergesundheit** [comment]
> Not sure if I understand it, then ¿Are you ok with what I am proposing?

should be fine :) :+1:

**Pull request merged**
