### PR TITLE
Improve rendering of certificate orgs in key pairs table

### PR DESCRIPTION
**Pull request by marians**
- Splits multiple orgs, sorts them
- Highlights the cluster-admin org name `system:masters` (but not `systems:master` ;-))

### Before

image

### After

image

### CODE REVIEW

**Comment by marians** [comment]
@wind0r kindly suggested this.

**Comment by oponder** [comment]
Nice!

I feel like the highlight `isadmin` state is a bit too harsh.. can we get away with something more subtle?

I think this is also a good opportunity to use a `React.PureComponent` instead of `React.Component`. https://reactjs.org/docs/react-api.html#reactpurecomponent

**Comment by oponder** [comment]
you could try something like `border-left: 4px solid #6f0316` on those isadmin labels, so they get a bit of a smaller indication that they're special?

Screenshot 2019-04-12 at 21 06 52

(messed around quickly in the dev console for demonstration of what that looks like)

**Comment by marians** [comment]
image

Toned down the red a little bit.

Also removed the nested `code` element to not have less DOM bloat.

**Pull request merged**
