### PR TITLE
Refactor the `<Button />` component to use `grommet`

### PR DESCRIPTION
**Pull request by axbarsan**
This PR refactors the `<Button />` component to use `grommet` as a base, instead of `bootstrap`. It also updates the component props to have the same interface as the original `grommet` one, while adding extra support for loading animations and `danger`/`warning` states.

All the components that used `<Button />` had to be updated, hence the large number of changes.

I tested all the buttons in the app and everything behaves the same as before.
The look is a bit different, because the new buttons are slightly larger, and have slightly different colors (for better contrast).

A code review would take too much effort, so please take the app for a spin, or build and run `fe-docs` locally, and check there.

## Preview

<details>
<summary>Primary</summary>

image

image

</details>

<details>
<summary>Secondary</summary>

image

image

</details>

<details>
<summary>Danger</summary>

image

image

</details>

<details>
<summary>Link</summary>

image

image

</details>

<details>
<summary>Disabled</summary>

image

</details>

<details>
<summary>Loading</summary>

image

</details>

### CODE REVIEW

**Comment by kuosandys** [comment]
This looks really great! The contrast on the new loading buttons are much better as well 👍 

Btw I noticed some changes in spacing between buttons in some places - would this be a separate issue though?

**Comment by marians** [comment]
One thing I noticed is that the green buttons get darker on mouse-over. My expectation would be that they look more "active" on mouse-over. That could be done using a lighter green tone instead of a darker one.

**Comment by marians** [comment]
Using this branch with gauss, when I navigate to http://localhost:7000/organizations/giantswarm/clusters/new I see an exception.

image

image

**Comment by axbarsan** [comment]
> Using this branch with gauss, when I navigate to http://localhost:7000/organizations/giantswarm/clusters/new I see an exception.
> 
> image
> 
> image

That is because you have the `MAPI Cluster management` experiment turned on. This is unsupported on AWS.

**Comment by axbarsan** [comment]
> This looks really great! The contrast on the new loading buttons are much better as well 👍
> 
> Btw I noticed some changes in spacing between buttons in some places - would this be a separate issue though?

There is a change in spacing, because the old button used to always have a margin on the right. Have you noticed any buttons that were close together instead of spaced out?

**Comment by kuosandys** [comment]
> > This looks really great! The contrast on the new loading buttons are much better as well 👍
> > Btw I noticed some changes in spacing between buttons in some places - would this be a separate issue though?
> 
> There is a change in spacing, because the old button used to always have a margin on the right. Have you noticed any buttons that were close together instead of spaced out?

Just in 2 places: new cluster creation, and access control subject deletion
Screen Shot 2021-08-09 at 09 54 11
Screen Shot 2021-08-09 at 09 53 40

I haven't spotted it anywhere else

**Comment by axbarsan** [comment]
> > > This looks really great! The contrast on the new loading buttons are much better as well 👍
> > > Btw I noticed some changes in spacing between buttons in some places - would this be a separate issue though?
> > 
> > 
> > There is a change in spacing, because the old button used to always have a margin on the right. Have you noticed any buttons that were close together instead of spaced out?
> 
> Just in 2 places: new cluster creation, and access control subject deletion
> Screen Shot 2021-08-09 at 09 54 11
> Screen Shot 2021-08-09 at 09 53 40
> 
> I haven't spotted it anywhere else

Thank you for finding those. I fixed em

**Comment by axbarsan** [comment]
> One thing I noticed is that the green buttons get darker on mouse-over. My expectation would be that they look more "active" on mouse-over. That could be done using a lighter green tone instead of a darker one.

Good call 👍 Updated the code and the screenshots

**Comment by marians** [comment]
> That is because you have the `MAPI Cluster management` experiment turned on. This is unsupported on AWS.

True. I wasn't aware that this would break happa on AWS. I thought it would only affect Azure.

**Review by marians — APPROVED** [review]
Great!

**Pull request merged**
