### PR TITLE
Getting started changes

### PR DESCRIPTION
**Pull request by oponder**
Applies the changes discussed here: https://github.com/giantswarm/giantswarm/issues/5256

- [x] Remove "Getting Started" from the navigation
- [x] Align button naming to "Get Started" everywhere. (instead of "access")
- [x] Remove page 1 (kubectl instructions)
- [x] Add "Organizations" to the navigation
- [x] Change url from `/getting-started/` to `/organizations/:orgID/clusters/:clusterID/getting-started/`
- [x]  Let page 2 determine what cluster to show information about from the path
- [x] Remove cluster select dropdown from page 2 of the guide.

### CODE REVIEW

**Comment by pipo02mix** [comment]
Not related to your changes but I realized there is no space between some links in the last step

screenshot 2019-02-20 at 09 18 16

**Comment by marians** [comment]
The button alignment is odd:

image

**Comment by marians** [comment]
Just noticed that the responsive behaviour needs some improvement. With a wider viewport, the content is narrower than with a less wide viewport.

image

image

**Comment by marians** [comment]
Another suggestion:

image

- Move the "Congratulations" part to the last page
- Change the button label from `Continue` to `Finish` (or something else?)

This would give the last page a bit more of a purpose, plus it would make it slightly more attractive, and it would not raise the wrong expectation that something will be happening in the last step.

**Comment by oponder** [comment]
@marians thanks for the review!

I'll try to fix the responsiveness in a follow up PR

**Comment by marians** [comment]
Are you going to merge this soon? I'd like to do more tweaks on the buttons, but don't want to create any additional work with merge conflicts.

**Comment by oponder** [comment]
@marians I want to finish a 'version footer' branch before I do anymore big changes to happa. I don't mind merge conflicts. go ahead.

**Comment by marians** [comment]
@oponder You could add `<i className='fa fa-start'></i>` in the `Get Started` button(s) in this branch (for https://github.com/giantswarm/giantswarm/issues/5410)

**Pull request merged**
