### PR TITLE
Loading indicator naming

### PR DESCRIPTION
**Pull request by ograu**
Low dash instead of regular one

### CODE REVIEW

**Comment by oponder** [comment]
Sorry I didn't even notice that in the previous PR :P thx for fixing it :)

**Comment by oponder** [comment]
Sorry I didn't even notice that in the previous PR :P thx for fixing it :)

**Comment by oponder** [comment]
Yeah the old file is still in the tree:

https://github.com/giantswarm/happa/tree/acacb1887282ccdf839df5eb40c60c6f6eea86aa/src/components/UI

**Comment by ograu** [comment]
Sorry, now it is deleted

**Pull request merged**
