### PR TITLE
docs: add architecture overview and a couple recipes

### PR DESCRIPTION
**Pull request by axbarsan**
Towards https://github.com/giantswarm/giantswarm/issues/16650

This PR adds the first docs towards having the development documentation in `storybook`:
- Architecture overview
- Recipe on creating a new component
- Recipe on adding a new feature flag

I used `mermaid` for the graphs, as that is what we use on intranet, as well. I added a custom component for it because existing ones out there are either 5 years old, or full of security issues.

These can't be previewed in the browser, so here's a helping hand:

<details>
<summary>Architecture of REST API features</summary>

image

</details>

<details>
<summary>Architecture of MAPI features</summary>

image

</details>

Please bare with me on the layouts, as positioning in `mermaid` is just moving stuff around until it kinda looks good.

More to come.

### CODE REVIEW

**Review by kopiczko — APPROVED** [review]
Fine with me but it would be good if someone for the chapter had a look

**Comment by axbarsan** [comment]
Ping @giantswarm/chapter-front-end. Can I get some 👀 on this, please? 😬

**Review by marians — APPROVED** [review]
LGTM

**Review by oponder — APPROVED** [review]
LGTM! 👍

**Pull request merged**
