### PR TITLE
Try to fix a weird behaviour of the loading spinner.

### PR DESCRIPTION
**Pull request by oponder**
I only see it in production, but the small loading spinners for the catalogs are sometimes spinning off axis and it looks very silly.

### CODE REVIEW

**Comment by oponder** [comment]
Since I can't figure out on short notice why this is happening, I opt to remove these spinners from this location for now.

Clicking on an app catalog that hasn't loaded still brings you to a proper loading state for just that catalog. 

Once I figure out how to avoid this I can reintroduce these helpful little spinners again.

wacky

**Comment by ograu** [comment]
@oponder I think it is the origin of the transform, taking a look at it now

**Comment by ograu** [comment]
@oponder can't check it now cause after updating my testing api I lost again apps section in my local happa, ¿have you tried `transition-origin: center` in the image?

**Comment by oponder** [comment]
@ograu Id like to fix it in another PR, but just remove it for now

**Pull request merged**
