### PR TITLE
Es lint changes

### PR DESCRIPTION
**Pull request by ograu**
- Unreacheable code to warning, because I like to do early returns when debugging without needing to comment x lines of code below the `return`statement.
- Removed sort imports rule because I prefer to sort imports in custom ways (node modules, components, custom hooks, UI, styles)  or not ordering them at all

WDYT Marian?

### CODE REVIEW

**Comment by marians** [comment]
I think removing the sorting of imports will force us (or rather: you and Oliver) to think about them again. But if you prefer it that way, fine with me.

**Comment by marians** [comment]
Please also remove the dependency from package.json

**Comment by ograu** [comment]
> I think removing the sorting of imports will force us (or rather: you and Oliver) to think about them again. But if you prefer it that way, fine with me.

Yeah... actually as this is something that affects all of us who are contributing here, so we should decide it as a team.

Changing error to warning for now and will discuss it with Oliver when he's back.

**Comment by marians** [comment]
Cool!

**Pull request merged**
